# action.yml
name: 'Code Review with ChatGPT'
description: 'Automating code review using ChatGPT with Github Actions integration on PRs for code explanations.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
    SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
    CHATGPT_API_URL: ${{ secrets.CHATGPT_API_URL }}
    CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
    CHATGPT_DEPLOYMENT_ID: ${{ secrets.CHATGPT_DEPLOYMENT_ID }}
    GITHUB_PR_ID: ${{ github.event.number }}
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
    SONARQUBE_PROJECT_KEY:  ${{ secrets.SONARQUBE_PROJECT_KEY }}
